### ISSUE TITLE
Vexriscv global variable problem

### ISSUE THREAD

**Issue by dfigueir** [IObundle/iob-soc-opencryptolinux#24]
Boa tarde @PedroAntunes178,

Existe um problema no iob-soc-vexriscv em que variáveis globais criadas em C não podem ser usadas correctamente em Assembly. 
O código de debug está no branch [global-var-bug](https://github.com/IObundle/iob-soc-vexriscv/tree/global-var-bug).
Este código cria 3 variáveis globais de tipos diferentes no firmware.c: inicializada, não inicializada e read-only. Depois chama uma função no main chamada varPrinter que é uma função de Assembly que se encontra no firmware.S. Essa função chama a função de impressão printVar (definida no firmware.c) e passa as 3 variáveis globais como argumentos. Os valores impressos no terminal estão incorrectos.
O mesmo teste corre bem no iob-soc mas não no iob-soc-vexriscv.

Cumprimentos,
Diogo

**Comment by PedroAntunes178** [comment]
This was fixed.
@dfigueir Can you close the issue after verifying that it was fixed?
