### ISSUE TITLE
Linux shell not responding correctly to commands

### ISSUE THREAD

**Issue by zettasticks** [IObundle/iob-soc-opencryptolinux#61]
After entering the shell, the user must input the enter key twice in order to run any command (the first enter advances a line with the first character of the command outputted but nothing more happens) and there is an extra line with only a '#" before the shell accepts a new command.

Example (Enter indicates when the enter key was pressed):
```
Welcome to Buildroot
buildroot login: root [Enter]
r [Enter]
oot
login[73]: root login on 'console'
# mkdir test [Enter]
m [Enter]
kdir test 
# 
# ls [Enter]
l [Enter]
s
test 
# pwd [Enter]
p [Enter]
wd 
/root
# 
# 
```

**Comment by PedroAntunes178** [comment]
Hello,
This issue was fixed in IOb-SoC console in PR https://github.com/IObundle/iob-soc/pull/654.
And IOb-SoC-OpenCryptoLinux was updated with it in PR https://github.com/IObundle/iob-soc-opencryptolinux/pull/64.
